### ISSUE TITLE
Xcode project missing files that have been added to .gitignore

### ISSUE THREAD

**Issue by kdawgwilk** [tannernelson/vapor#20]
Forked the repo to hopefully help contribute but not sure how you would like this to occur.  The Xcode project seems pretty broken right now due to many missing files that are added in the `.gitignore`.  I am not able to run the current tests and not sure how you would like newly added tests to be added to the project.

**Comment by tannernelson** [comment]
The files included in the `.gitignore` are for development purposes only. Files like `main.swift` can't be included in the repo, or they will make the module compile as an executable instead of a library which will make it incompatible with the Swift Package Manager. 

You can copy the `main.swift` file from the [Example](https://github.com/tannernelson/vapor-example) repo. 

That should be the only file you need to make the Xcode project compile. All others are optional.
