### ISSUE TITLE
Stencil/Mustache parsing

### ISSUE THREAD

**Issue by tannernelson** [tannernelson/vapor#7]
Implement https://github.com/kylef/Stencil or other Mustache-like parsing for `View`s.

**Comment by kdawgwilk** [comment]
This seems like a great place to bring up middleware support for vapor.  
Some thoughts I have had on the subject
Would we want support for adding middleware to:
     - All requests
     - A single route
     - A group of routes
The `Bootstrap` class seems to be the place where middleware will hook into request and response to process what it needs to then pass it on.  The problem I see is that in order to add support for multiple layers of middleware we would also need access to the next middleware in line inside both methods of Bootstrap.  Also how middleware is ordered as it comes in from the request versus going out in the response should be decided.
Some links to where my thoughts/ideas are coming from:
SlimPHP's middleware [docs](http://www.slimframework.com/docs/concepts/middleware.html)
Lumen's middleware [docs](https://lumen.laravel.com/docs/5.2/middleware)

**Comment by tannernelson** [comment]
I'm working on an update that replaces `Bootstrap` and adds a protocol called `Middleware`.

This will be in release `0.1.7`.

The protocol looks like this

```swift
public protocol Middleware {
    func handle(handler: Request -> Response) -> (Request -> Response)   
}
```

**Comment by tannernelson** [comment]
Stencil parsing added in `0.1.8`

**Comment by yudun1989** [comment]
@tannernelson  vapor had stopped support for stencil template?

**Comment by LoganWright** [comment]
@yudun1989 the efforts required to run stencil on Linux were insurmountable for a long time w/o maintaining multiple forks in the dependency chain of Stencil. I'm not sure the current Linux status, but if it's improved, making a 3rd party stencil provider shouldn't be too difficult.

Unfortunately, these 3rd party renderers were requiring too much dev time internally, so it's very unlikely that we'll open up official support any time soon.

Hopefully this answers your question, and happy to open a discussion further if you'd like 👍
